# Generated by Django 2.0 on 2020-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название фильма')),
                ('descr', models.TextField(null=True, verbose_name='Описание фильма')),
                ('year', models.IntegerField(null=True, verbose_name='Год выхода')),
            ],
        ),
    ]
